package com.kovian.finance.recurring.api;
import com.kovian.finance.recurring.domain.*; import com.kovian.finance.recurring.repository.*; import com.kovian.finance.account.repository.*; import com.kovian.finance.category.repository.*; import com.kovian.finance.transaction.domain.*; import com.kovian.finance.transaction.repository.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*; import java.math.*;
@RestController @RequestMapping("/api/v1/recurring") public class RecurringTransactionController {
final RecurringTransactionRepository recurring; final FinancialAccountRepository accounts; final TransactionCategoryRepository categories; final FinancialTransactionRepository transactions;
public RecurringTransactionController(RecurringTransactionRepository r,FinancialAccountRepository a,TransactionCategoryRepository c,FinancialTransactionRepository t){recurring=r;accounts=a;categories=c;transactions=t;}
record Request(UUID ownerId,UUID accountId,UUID categoryId,String description,BigDecimal amount,TransactionType transactionType,RecurringFrequency frequency,LocalDate nextOccurrence,LocalDate endDate){}
@PostMapping @Transactional public RecurringTransaction create(@RequestBody Request r){var account=accounts.findByIdAndOwnerId(r.accountId(),r.ownerId()).orElseThrow(()->new IllegalArgumentException("Account does not belong to owner")); if(r.categoryId()!=null)categories.findByIdAndOwnerId(r.categoryId(),r.ownerId()).orElseThrow(()->new IllegalArgumentException("Category does not belong to owner")); return recurring.save(new RecurringTransaction(r.ownerId(),r.accountId(),r.categoryId(),r.description(),r.amount(),r.transactionType(),r.frequency(),r.nextOccurrence(),r.endDate()));}
@GetMapping public List<RecurringTransaction> list(@RequestParam UUID ownerId){return recurring.findByOwnerIdOrderByNextOccurrence(ownerId);}
@PostMapping("/{id}/pause") @Transactional public void pause(@PathVariable UUID id,@RequestParam UUID ownerId){recurring.findByIdAndOwnerId(id,ownerId).orElseThrow().pause();}
@PostMapping("/{id}/resume") @Transactional public void resume(@PathVariable UUID id,@RequestParam UUID ownerId){recurring.findByIdAndOwnerId(id,ownerId).orElseThrow().resume();}
@PostMapping("/process-due") @Transactional public int processDue(@RequestParam LocalDate date){int count=0;for(var r:recurring.findByActiveTrueAndNextOccurrenceLessThanEqual(date)){while(r.isActive()&&!r.getNextOccurrence().isAfter(date)){var key="recurring:"+r.getId()+":"+r.getNextOccurrence();if(!transactions.existsByOwnerIdAndExternalId(r.getOwnerId(),key)){var account=accounts.findByIdAndOwnerId(r.getAccountId(),r.getOwnerId()).orElseThrow();var category=r.getCategoryId()==null?null:categories.findByIdAndOwnerId(r.getCategoryId(),r.getOwnerId()).orElseThrow();transactions.save(new FinancialTransaction(r.getOwnerId(),account,category,key,r.getDescription(),r.getAmount(),r.getTransactionType(),r.getNextOccurrence().atStartOfDay().atOffset(ZoneOffset.UTC)));if(r.getTransactionType()==TransactionType.INCOME)account.applyIncome(r.getAmount());else account.applyExpense(r.getAmount());}r.advance();count++;}}return count;}
}