spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      url: ${REDIS_URL}
  flyway:
    validate-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
server:
  forward-headers-strategy: framework
  error:
    include-message: never
    include-stacktrace: never
kovian:
  kovi:
    internal-api-key: ${KOVI_INTERNAL_API_KEY}
