package com.kovian.finance.card.domain;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.OffsetDateTime; import java.util.UUID;
@Entity @Table(name="credit_cards")
public class CreditCard {
 @Id @GeneratedValue(strategy=GenerationType.UUID) UUID id; @Column(name="owner_id",nullable=false) UUID ownerId; @Column(nullable=false) String name; String brand; @Column(name="last_four",length=4) String lastFour; @Column(name="credit_limit",precision=19,scale=4,nullable=false) BigDecimal creditLimit; @Column(name="closing_day",nullable=false,columnDefinition="smallint") int closingDay; @Column(name="due_day",nullable=false,columnDefinition="smallint") int dueDay; @Enumerated(EnumType.STRING) @Column(nullable=false) CreditCardStatus status=CreditCardStatus.ACTIVE; @Column(name="created_at",nullable=false) OffsetDateTime createdAt=OffsetDateTime.now(); @Column(name="updated_at",nullable=false) OffsetDateTime updatedAt=OffsetDateTime.now();
 protected CreditCard(){} public CreditCard(UUID o,String n,String b,String l,BigDecimal limit,int close,int due){if(o==null||n==null||n.isBlank()||limit==null||limit.signum()<0||close<1||close>31||due<1||due>31)throw new IllegalArgumentException("Invalid credit card");ownerId=o;name=n.trim();brand=b;lastFour=l;creditLimit=limit;closingDay=close;dueDay=due;}
 public UUID getId(){return id;} public UUID getOwnerId(){return ownerId;} public String getName(){return name;} public String getBrand(){return brand;} public String getLastFour(){return lastFour;} public BigDecimal getCreditLimit(){return creditLimit;} public int getClosingDay(){return closingDay;} public int getDueDay(){return dueDay;} public CreditCardStatus getStatus(){return status;}
 public void block(){status=CreditCardStatus.BLOCKED;updatedAt=OffsetDateTime.now();} public void archive(){status=CreditCardStatus.ARCHIVED;updatedAt=OffsetDateTime.now();}
}
