package com.kovian.finance.card.api;
import com.kovian.finance.card.domain.*; import com.kovian.finance.card.repository.*; import com.kovian.finance.account.repository.*; import com.kovian.finance.transaction.domain.*; import com.kovian.finance.transaction.repository.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/v1/cards") public class CreditCardController {
final CreditCardRepository cards; final CreditCardInvoiceRepository invoices; final CreditCardPurchaseRepository purchases; final FinancialAccountRepository accounts; final FinancialTransactionRepository transactions;
public CreditCardController(CreditCardRepository c,CreditCardInvoiceRepository i,CreditCardPurchaseRepository p,FinancialAccountRepository a,FinancialTransactionRepository t){cards=c;invoices=i;purchases=p;accounts=a;transactions=t;}
record CardRequest(UUID ownerId,String name,String brand,String lastFour,BigDecimal creditLimit,int closingDay,int dueDay){}
record PurchaseRequest(UUID ownerId,UUID cardId,String description,BigDecimal totalAmount,int installments,LocalDate purchasedAt){}
@PostMapping @Transactional public CreditCard create(@RequestBody CardRequest r){return cards.save(new CreditCard(r.ownerId(),r.name(),r.brand(),r.lastFour(),r.creditLimit(),r.closingDay(),r.dueDay()));}
@GetMapping public List<CreditCard> list(@RequestParam UUID ownerId){return cards.findByOwnerIdOrderByName(ownerId);}
@PostMapping("/purchases") @Transactional public CreditCardPurchase purchase(@RequestBody PurchaseRequest r){var card=cards.findByIdAndOwnerId(r.cardId(),r.ownerId()).orElseThrow();if(card.getStatus()!=CreditCardStatus.ACTIVE||r.totalAmount()==null||r.totalAmount().signum()<=0||r.installments()<1)throw new IllegalArgumentException("Invalid card purchase");var date=r.purchasedAt()==null?LocalDate.now():r.purchasedAt();var base=r.totalAmount().divide(BigDecimal.valueOf(r.installments()),4,RoundingMode.HALF_UP);CreditCardPurchase first=null;for(int n=1;n<=r.installments();n++){var month=date.withDayOfMonth(1).plusMonths(n-1);var close=month.withDayOfMonth(Math.min(card.getClosingDay(),month.lengthOfMonth()));var dueMonth=month.plusMonths(1);var due=dueMonth.withDayOfMonth(Math.min(card.getDueDay(),dueMonth.lengthOfMonth()));var inv=invoices.findByCardIdAndReferenceMonth(card.getId(),month).orElseGet(()->invoices.save(new CreditCardInvoice(r.ownerId(),card.getId(),month,close,due)));var amount=n==r.installments()?r.totalAmount().subtract(base.multiply(BigDecimal.valueOf(n-1))):base;inv.addAmount(amount);invoices.save(inv);var p=purchases.save(new CreditCardPurchase(r.ownerId(),card.getId(),inv.getId(),r.description(),r.totalAmount(),amount,n,r.installments(),date));if(first==null)first=p;}return first;}
@GetMapping("/invoices") public List<CreditCardInvoice> invoices(@RequestParam UUID ownerId){return invoices.findByOwnerIdOrderByDueDate(ownerId);}
@GetMapping("/invoices/{id}/purchases") public List<CreditCardPurchase> purchases(@PathVariable UUID id){return purchases.findByInvoiceIdOrderById(id);}
@PostMapping("/invoices/{id}/close") @Transactional public void close(@PathVariable UUID id,@RequestParam UUID ownerId){invoices.findByIdAndOwnerId(id,ownerId).orElseThrow().close();}
@PostMapping("/invoices/{id}/pay") @Transactional public void pay(@PathVariable UUID id,@RequestParam UUID ownerId,@RequestParam UUID accountId){var inv=invoices.findByIdAndOwnerId(id,ownerId).orElseThrow();if(inv.getStatus()==InvoiceStatus.PAID)throw new IllegalArgumentException("Invoice already paid");var account=accounts.findByIdAndOwnerId(accountId,ownerId).orElseThrow(()->new IllegalArgumentException("Account does not belong to owner"));var key="card-invoice:"+inv.getId();if(!transactions.existsByOwnerIdAndExternalId(ownerId,key)){transactions.save(new FinancialTransaction(ownerId,account,null,key,"Credit card invoice payment",inv.getTotalAmount(),TransactionType.EXPENSE,inv.getDueDate().atStartOfDay().atOffset(ZoneOffset.UTC)));account.applyExpense(inv.getTotalAmount());}inv.markPaid();}
}