package com.kovian.finance.notification.application;
import com.kovian.finance.card.domain.CreditCardInvoice; import com.kovian.finance.card.repository.CreditCardInvoiceRepository; import com.kovian.finance.debt.domain.*; import com.kovian.finance.debt.repository.DebtRepository; import com.kovian.finance.goal.domain.FinancialGoal; import com.kovian.finance.goal.repository.FinancialGoalRepository; import com.kovian.finance.recurring.domain.RecurringTransaction; import com.kovian.finance.recurring.repository.RecurringTransactionRepository; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class FinancialDueRules{
 private final CreditCardInvoiceRepository invoices; private final DebtRepository debts; private final RecurringTransactionRepository recurring; private final FinancialGoalRepository goals; private final NotificationService notifications;
 public FinancialDueRules(CreditCardInvoiceRepository i,DebtRepository d,RecurringTransactionRepository r,FinancialGoalRepository g,NotificationService n){invoices=i;debts=d;recurring=r;goals=g;notifications=n;}
 @Transactional public void evaluate(LocalDate today){
  LocalDate horizon=today.plusDays(3);
  invoices.findAll().stream().filter(i->i.getDueDate()!=null&&!i.getStatus().name().equals("PAID")&&!i.getDueDate().isBefore(today)&&!i.getDueDate().isAfter(horizon)).forEach(i->notify(i.getOwnerId(),"CARD_INVOICE_DUE","WARNING","Fatura do cartão próxima do vencimento","A fatura vence em "+i.getDueDate()+".","CreditCardInvoice",i.getId(),"card:"+i.getId()+":"+i.getDueDate()));
  recurring.findAll().stream().filter(r->r.isActive()&&!r.getNextOccurrence().isAfter(horizon)).forEach(r->notify(r.getOwnerId(),"RECURRING_DUE","INFO","Lançamento recorrente próximo","Existe um lançamento recorrente previsto para "+r.getNextOccurrence()+".","RecurringTransaction",r.getId(),"recurring:"+r.getId()+":"+r.getNextOccurrence()));
  debts.findAll().stream().filter(d->d.getStatus()==DebtStatus.ACTIVE).forEach(d->notify(d.getOwnerId(),"DEBT_ACTIVE","INFO","Dívida em aberto","A dívida possui saldo pendente de "+d.getOutstandingAmount()+".","Debt",d.getId(),"debt:"+d.getId()+":"+today));
  goals.findAll().stream().filter(FinancialGoal::isActive).filter(g->g.getTargetDate()!=null&&g.getTargetDate().isBefore(today.plusDays(30).atStartOfDay().atOffset(ZoneOffset.UTC))).forEach(g->notify(g.getOwnerId(),"GOAL_DEADLINE","WARNING","Meta financeira próxima do prazo","A meta está próxima da data planejada.","FinancialGoal",g.getId(),"goal:"+g.getId()+":"+g.getTargetDate()));
 }
 private void notify(UUID owner,String type,String severity,String title,String message,String entity,UUID id,String key){notifications.createForOwner(owner,type,severity,title,message,entity,id,key);}
}