import { useEffect, useRef, useState, type ReactNode } from 'react'
import { useFinanceOwnerId } from '../lib/useFinanceOwnerId'
import { NavLink } from 'react-router-dom'
import { ArrowDownLeft, ArrowUpRight, BarChart3, CalendarClock, ChevronRight, CreditCard, FolderTree, Plus, Receipt, ShieldCheck, Settings2, Sparkles, Target, Wallet } from 'lucide-react'
import { closeInvoice, createAccount, createBudget, createCard, createCardPurchase, createCategory, createGoal, createRecurring, createTransaction, cancelTransaction, getAccounts, getAnalytics, getBudgets, getCards, getCategories, getCategoryAnalytics, getGoals, getInvoicePurchases, getInvoices, getRecurring, getTransactions, getReconciliationHistory, reconcileAccount, payInvoice, pauseRecurring, resumeRecurring, type ReconciliationRun, type FinanceAccount, type FinanceAnalytics, type FinanceBudget, type FinanceCard, type FinanceCategory, type FinanceGoal, type FinanceInvoice, type FinancePurchase, type FinanceRecurring, type FinanceTransaction } from '../lib/api'
import LanguageSwitcher from '../components/LanguageSwitcher'
import PageHeader from '../components/ui/PageHeader'
import { budgetPercent, budgetRemaining, budgetSpent, categoryTree, periodBounds, periodStartFor } from '../lib/budgetUtils'
import { useTranslation } from 'react-i18next'
import Modal from '../components/ui/Modal'
import Field from '../components/ui/Field'
import { useFinanceDashboard, useFinanceMutation } from '../lib/queries'
import { formatCurrency as money } from '../lib/format'

const getLocale = () => typeof document !== 'undefined' ? (document.documentElement.lang || 'pt-BR') : 'pt-BR'
const isPositiveAmount = (value: string) => Number.isFinite(Number(value)) && Number(value) > 0
const newTransactionExternalId = () => typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `txn-${Date.now()}-${Math.random().toString(36).slice(2)}`
const localDateKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
export function Header({ title, desc, action }: { title: string; desc: string; action?: ReactNode }) { return <PageHeader title={title} description={desc} actions={action} /> }
export function Dashboard() {
  const { t } = useTranslation()
  const ownerId = useFinanceOwnerId()
  const dashboard = useFinanceDashboard(ownerId)
  const accounts = dashboard.accounts.data ?? []
  const goals = dashboard.goals.data ?? []
  const transactions = dashboard.transactions.data ?? []
  const analytics = dashboard.analytics.data
  const loading = dashboard.isLoading
  const error = ownerId ? (dashboard.isError ? t('financeLoadError') : null) : t('loginToLoadData')
  const brlIds = new Set(accounts.filter(account => account.currency === 'BRL').map(account => account.id))
  const brlTx = transactions.filter(transaction => brlIds.has(transaction.accountId) && transaction.status !== 'CANCELLED')
  const balance = accounts.filter(account => account.currency === 'BRL').reduce((sum, account) => sum + Number(account.currentBalance || 0), 0)
  const allAccountsBrl = accounts.length > 0 && accounts.every(account => account.currency === 'BRL')
  const income = allAccountsBrl && analytics ? Number(analytics.income) : brlTx.filter(tx => tx.type === 'INCOME').reduce((sum, tx) => sum + Number(tx.amount || 0), 0)
  const expense = allAccountsBrl && analytics ? Number(analytics.expense) : brlTx.filter(tx => tx.type === 'EXPENSE').reduce((sum, tx) => sum + Number(tx.amount || 0), 0)
  const activeGoals = goals.filter(goal => goal.active)
  const targetTotal = activeGoals.reduce((sum, goal) => sum + Number(goal.targetAmount || 0), 0)
  const savedTotal = activeGoals.reduce((sum, goal) => sum + Number(goal.currentAmount || 0), 0)
  const goalProgress = targetTotal > 0 ? Math.min(100, Math.round(savedTotal / targetTotal * 100)) : 0
  const recentTransactions = [...brlTx].sort((a, b) => new Date(b.occurredAt).getTime() - new Date(a.occurredAt).getTime()).slice(0, 6)
  const monthBuckets = Array.from({ length: 3 }, (_, index) => {
    const date = new Date()
    date.setDate(1)
    date.setMonth(date.getMonth() - (2 - index))
    const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
    const monthTransactions = brlTx.filter(tx => tx.occurredAt.slice(0, 7) === key)
    return { key, label: date.toLocaleDateString(getLocale(), { month: 'short' }), income: monthTransactions.filter(tx => tx.type === 'INCOME').reduce((sum, tx) => sum + Number(tx.amount), 0), expense: monthTransactions.filter(tx => tx.type === 'EXPENSE').reduce((sum, tx) => sum + Number(tx.amount), 0) }
  })
  const chartMax = Math.max(1, ...monthBuckets.flatMap(bucket => [bucket.income, bucket.expense]))
  return <main className="page">
    <Header title={t('financeHeroTitle')} desc={t('financeHeroDesc')} action={<NavLink className="primary" to="/transacoes"><Plus size={17} /> {t('newTransaction')}</NavLink>} />
    {error && <div className="notice" role="status" aria-live="polite"><ShieldCheck size={18} /><span>{error}</span></div>}
    <section className="hero-card" aria-labelledby="finance-balance-title"><div><span id="finance-balance-title">{t('consolidatedBalance')} · BRL</span><strong>{loading ? t('loading') : money(balance, 'BRL')}</strong><small>{t('activeAccounts', { count: accounts.length })}</small></div><div className="hero-orb"><Wallet size={25} /></div></section>
    <div className="stat-grid" aria-label={t('quickAccess')}>
      <Stat label={t('income90Days')} value={loading ? '—' : money(income, 'BRL')} icon={ArrowDownLeft} />
      <Stat label={t('expense90Days')} value={loading ? '—' : money(expense, 'BRL')} icon={ArrowUpRight} />
      <Stat label={t('cashFlow90Days')} value={loading ? '—' : money(income - expense, 'BRL')} icon={BarChart3} />
      <Stat label={t('activeGoals')} value={loading ? '—' : String(activeGoals.length)} icon={Target} />
    </div>
    <section className="panel data-panel">
      <div className="section-title"><div><span className="eyebrow">{t('overview')}</span><h2>{t('cashFlow90Days')}</h2></div><span className="badge">{t('lastThreeMonths')}</span></div>
      {loading ? <div className="empty-inline">{t('loading')}</div> : <div className="dashboard-month-chart" role="img" aria-label={t('incomeExpenseChart')}>
        {monthBuckets.map(bucket => <div className="dashboard-month" key={bucket.key}>
          <div className="dashboard-bars"><span className="dashboard-bar income" title={`${t('income')}: ${money(bucket.income, 'BRL')}`} style={{ height: `${Math.max(bucket.income > 0 ? 4 : 0, bucket.income / chartMax * 100)}%` }} /><span className="dashboard-bar expense" title={`${t('expense')}: ${money(bucket.expense, 'BRL')}`} style={{ height: `${Math.max(bucket.expense > 0 ? 4 : 0, bucket.expense / chartMax * 100)}%` }} /></div>
          <strong>{bucket.label}</strong><small>{money(bucket.income - bucket.expense, 'BRL')}</small>
        </div>)}
      </div>}
      <div className="dashboard-chart-legend"><span><i className="income" />{t('income')}</span><span><i className="expense" />{t('expense')}</span></div>
    </section>
    <section className="panel data-panel">
      <div className="section-title"><div><span className="eyebrow">{t('objectives')}</span><h2>{t('goalsProgress')}</h2></div><NavLink to="/metas">{t('viewAll')} <ChevronRight size={15} /></NavLink></div>
      {activeGoals.slice(0, 3).map(goal => { const target = Number(goal.targetAmount); const saved = Number(goal.currentAmount); const percent = target > 0 ? Math.min(100, Math.round(saved / target * 100)) : 0; return <div className="budget-row" key={goal.id}><div className="budget-row-head"><span><strong>{goal.name}</strong><small>{money(saved, 'BRL')} / {money(target, 'BRL')}</small></span><span>{percent}%</span></div><div className="budget-progress"><span style={{ width: `${percent}%` }} /></div></div> })}
      {!loading && !activeGoals.length && <div className="empty-inline">{t('noActiveGoals')} <NavLink to="/metas">{t('goalsNew')}</NavLink></div>}
      <div className="dashboard-goal-total"><span>{t('goalsOverallProgress')}</span><strong>{loading ? '—' : `${goalProgress}%`}</strong></div>
    </section>
    <section className="panel data-panel">
      <div className="section-title"><div><span className="eyebrow">{t('activity')}</span><h2>{t('recentTransactions')}</h2></div><NavLink to="/transacoes">{t('viewAll')} <ChevronRight size={15} /></NavLink></div>
      {recentTransactions.map(tx => <div className="account-row" key={tx.id}><i /><span><strong>{tx.description}</strong><small>{new Date(tx.occurredAt).toLocaleDateString(getLocale())} · {accounts.find(account => account.id === tx.accountId)?.name ?? t('account')}</small></span><b className={tx.type === 'INCOME' ? 'positive' : 'negative'}>{tx.type === 'INCOME' ? '+' : '−'} {money(Number(tx.amount), 'BRL')}</b></div>)}
      {!loading && !recentTransactions.length && <div className="empty-inline">{t('noMovements')}</div>}
    </section>
    <section className="panel"><div className="section-title"><div><span className="eyebrow">{t('accounts')}</span><h2>{t('connectedAccounts')}</h2></div><NavLink to="/contas">{t('viewAll')} <ChevronRight size={15} /></NavLink></div><div className="account-list">{accounts.slice(0, 5).map(account => <div className="account-row" key={account.id}><i /><span><strong>{account.name}</strong><small>{account.accountType} · {account.currency}</small></span><b>{money(Number(account.currentBalance || 0), account.currency)}</b></div>)}{!loading && !accounts.length && <div className="empty-inline">{t('noAccounts')}</div>}</div></section>
  </main>
}
function Stat({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Target }) { return <article className="stat-card"><Icon size={17} /><span>{label}</span><strong>{value}</strong></article> }
export const pageConfig: Record<string, { titleKey: string; descKey: string; icon: typeof Wallet; itemKeys: string[]; actionTo: string; itemRoutes: string[] }> = {
  '/contas': { titleKey: 'pages.accounts.title', descKey: 'pages.accounts.desc', icon: Wallet, itemKeys: ['pages.accounts.items.bank','pages.accounts.items.wallets','pages.accounts.items.balances'], actionTo: '/contas', itemRoutes: ['/contas','/contas','/contas'] },
  '/transacoes': { titleKey: 'pages.transactions.title', descKey: 'pages.transactions.desc', icon: Receipt, itemKeys: ['pages.transactions.items.incomeExpense','pages.transactions.items.filters','pages.transactions.items.categories'], actionTo: '/transacoes', itemRoutes: ['/transacoes','/transacoes','/transacoes'] },
  '/metas': { titleKey: 'pages.goals.title', descKey: 'pages.goals.desc', icon: Target, itemKeys: ['pages.goals.items.emergency','pages.goals.items.custom','pages.goals.items.monthly'], actionTo: '/metas', itemRoutes: ['/metas','/metas','/metas'] },
  '/relatorios': { titleKey: 'pages.reports.title', descKey: 'pages.reports.desc', icon: BarChart3, itemKeys: ['pages.reports.items.cashflow','pages.reports.items.period','pages.reports.items.categories'], actionTo: '/relatorios', itemRoutes: ['/relatorios','/relatorios','/relatorios'] },
  '/cartoes': { titleKey: 'pages.cards.title', descKey: 'pages.cards.desc', icon: CreditCard, itemKeys: ['pages.cards.items.cards','pages.cards.items.invoices','pages.cards.items.installments'], actionTo: '/cartoes', itemRoutes: ['/cartoes','/cartoes','/cartoes'] },
  '/orcamentos': { titleKey: 'pages.budgets.title', descKey: 'pages.budgets.desc', icon: Target, itemKeys: ['pages.budgets.items.monthly','pages.budgets.items.limits','pages.budgets.items.alerts'], actionTo: '/orcamentos', itemRoutes: ['/orcamentos','/orcamentos','/orcamentos'] },
  '/recorrentes': { titleKey: 'pages.recurring.title', descKey: 'pages.recurring.desc', icon: CalendarClock, itemKeys: ['pages.recurring.items.expenses','pages.recurring.items.income','pages.recurring.items.due'], actionTo: '/recorrentes', itemRoutes: ['/recorrentes','/recorrentes','/recorrentes'] },
  '/categorias': { titleKey: 'pages.categories.title', descKey: 'pages.categories.desc', icon: FolderTree, itemKeys: ['pages.categories.items.expenses','pages.categories.items.income','pages.categories.items.tags'], actionTo: '/categorias', itemRoutes: ['/categorias','/categorias','/categorias'] },
  '/configuracoes': { titleKey: 'pages.settings.title', descKey: 'pages.settings.desc', icon: Settings2, itemKeys: ['pages.settings.items.profile','pages.settings.items.security','pages.settings.items.preferences'], actionTo: '/configuracoes', itemRoutes: ['/configuracoes','/configuracoes','/configuracoes'] },
}
export const pageTranslationKeys: Record<string, [string, string]> = { '/contas':['pages.accounts.title','pages.accounts.desc'], '/transacoes':['pages.transactions.title','pages.transactions.desc'], '/metas':['pages.goals.title','pages.goals.desc'], '/relatorios':['pages.reports.title','pages.reports.desc'], '/cartoes':['pages.cards.title','pages.cards.desc'], '/orcamentos':['pages.budgets.title','pages.budgets.desc'], '/recorrentes':['pages.recurring.title','pages.recurring.desc'], '/categorias':['pages.categories.title','pages.categories.desc'], '/configuracoes':['pages.settings.title','pages.settings.desc'] }
export function FinancePage({ config }: { config: typeof pageConfig[string] }) {
  const { t } = useTranslation()
  const ownerId = useFinanceOwnerId()
  const [accounts, setAccounts] = useState<FinanceAccount[]>([])
  const [transactions, setTransactions] = useState<FinanceTransaction[]>([])
  const [goals, setGoals] = useState<FinanceGoal[]>([])
  const [cards, setCards] = useState<FinanceCard[]>([])
  const [reconciliationRuns, setReconciliationRuns] = useState<ReconciliationRun[]>([])
  const [invoices, setInvoices] = useState<FinanceInvoice[]>([])
  const [purchases, setPurchases] = useState<FinancePurchase[]>([])
  const [selectedInvoice, setSelectedInvoice] = useState<string | null>(null)
  const [categories, setCategories] = useState<FinanceCategory[]>([])
  const [budgets, setBudgets] = useState<FinanceBudget[]>([])
  const [recurring, setRecurring] = useState<FinanceRecurring[]>([])
  const [analytics, setAnalytics] = useState<FinanceAnalytics | null>(null)
  const [categoryAnalytics, setCategoryAnalytics] = useState<Record<string, number>>({})
  const [loading, setLoading] = useState(false)
  const [modal, setModal] = useState<'transaction' | 'account' | 'category' | 'budget' | 'goal' | 'recurring' | 'card' | 'cardPurchase' | 'invoicePayment' | null>(null)
  const [saving, setSaving] = useState(false)
  const savingLock = useRef(false)
  const [refreshVersion, setRefreshVersion] = useState(0)
  const [formError, setFormError] = useState<string | null>(null)
  const [loadError, setLoadError] = useState<string | null>(null)
  const [description, setDescription] = useState('')
  const [transactionSearch, setTransactionSearch] = useState('')
  const [transactionAccountFilter, setTransactionAccountFilter] = useState('')
  const [transactionTypeFilter, setTransactionTypeFilter] = useState<'ALL' | 'INCOME' | 'EXPENSE'>('ALL')
  const [occurredAtDate, setOccurredAtDate] = useState(localDateKey())
  const [transactionExternalId, setTransactionExternalId] = useState(newTransactionExternalId)
  const [amount, setAmount] = useState('')
  const [accountId, setAccountId] = useState('')
  const [categoryId, setCategoryId] = useState('')
  const [transactionType, setTransactionType] = useState<'INCOME' | 'EXPENSE'>('EXPENSE')
  const [name, setName] = useState('')
  const [accountNameValue, setAccountNameValue] = useState('')
  const accountNameInput = useRef<HTMLInputElement>(null)
  const [accountType, setAccountType] = useState('CHECKING')
  const [openingBalance, setOpeningBalance] = useState('0')
  const [currency, setCurrency] = useState('BRL')
  const [categoryKind, setCategoryKind] = useState<FinanceCategory['kind']>('EXPENSE')
  const [parentCategoryId, setParentCategoryId] = useState('')
  const [categoryFilter, setCategoryFilter] = useState<FinanceCategory['kind']>('EXPENSE')
  const [period, setPeriod] = useState<FinanceBudget['period']>('MONTHLY')
  const [targetDate, setTargetDate] = useState('')
  const [frequency, setFrequency] = useState('MONTHLY')
  const [nextOccurrence, setNextOccurrence] = useState(localDateKey())
  const [endDate, setEndDate] = useState('')
  const [cardBrand, setCardBrand] = useState('Visa')
  const [lastFour, setLastFour] = useState('')
  const [creditLimit, setCreditLimit] = useState('')
  const [closingDay, setClosingDay] = useState('10')
  const [dueDay, setDueDay] = useState('20')
  const [cardId, setCardId] = useState('')
  const [installments, setInstallments] = useState('1')
  const [invoicePaymentId, setInvoicePaymentId] = useState('')
  const resetForm = () => { setName(''); setAccountNameValue(''); setDescription(''); setTransactionSearch(''); setTransactionAccountFilter(''); setTransactionTypeFilter('ALL'); setOccurredAtDate(localDateKey()); setTransactionExternalId(newTransactionExternalId()); setAmount(''); setOpeningBalance('0'); setFormError(null); setTargetDate(''); setLastFour(''); setCreditLimit(''); setClosingDay('10'); setDueDay('20'); setInstallments('1'); setParentCategoryId(''); setAccountId(''); setCategoryId(''); setTransactionType('EXPENSE'); setCurrency('BRL'); setCategoryKind('EXPENSE'); setCategoryFilter('EXPENSE'); setPeriod('MONTHLY'); setCardId(''); setInvoicePaymentId(''); setFrequency('MONTHLY'); setNextOccurrence(localDateKey()); setEndDate('') }
  useEffect(() => {
    if (!ownerId) return
    setLoading(true)
    setLoadError(null)
    const now = new Date(); const from = new Date(now.getFullYear(), now.getMonth(), 1); const to = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999)
    const monthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 1)
    const fromIso = from.toISOString(); const toIso = to.toISOString(); const monthEndIso = monthEnd.toISOString(); const fromDate = localDateKey(from); const toDate = localDateKey(to)
    const load = config.actionTo === '/contas' ? Promise.all([getAccounts(ownerId), getReconciliationHistory()]).then(([a, runs]) => { setAccounts(a); setReconciliationRuns(runs) }) : config.actionTo === '/transacoes' ? Promise.all([getAccounts(ownerId), getCategories(ownerId, 'EXPENSE'), getCategories(ownerId, 'INCOME'), getTransactions(fromIso, toIso)]).then(([a, e, i, tr]) => { setAccounts(a); setCategories([...e, ...i]); setTransactions(tr) }) : config.actionTo === '/metas' ? getGoals(ownerId).then(setGoals) : config.actionTo === '/cartoes' ? Promise.all([getCards(ownerId), getInvoices(ownerId), getAccounts(ownerId)]).then(([c, i, a]) => { setCards(c); setInvoices(i); setAccounts(a) }) : config.actionTo === '/categorias' ? Promise.all([getCategories(ownerId, 'EXPENSE'), getCategories(ownerId, 'INCOME')]).then(([e, i]) => setCategories([...e, ...i])) : config.actionTo === '/orcamentos' ? Promise.all([getBudgets(ownerId, new Date(now.getFullYear(), 0, 1).toISOString(), new Date(now.getFullYear() + 1, 0, 1).toISOString()), getCategories(ownerId, 'EXPENSE')]).then(async ([allBudgets, c]) => { const currentBudgets = allBudgets.filter(b => periodStartFor(b.period, now).toISOString().slice(0, 10) === new Date(b.periodStart).toISOString().slice(0, 10)); const bounds = currentBudgets.map(periodBounds); const transactionFrom = bounds.length ? new Date(Math.min(...bounds.map(b => b.from.getTime()))) : from; const transactionTo = bounds.length ? new Date(Math.max(...bounds.map(b => b.to.getTime()))) : monthEnd; const tr = await getTransactions(transactionFrom.toISOString(), transactionTo.toISOString()); setBudgets(currentBudgets); setCategories(c); setTransactions(tr) }) : config.actionTo === '/recorrentes' ? Promise.all([getRecurring(), getAccounts(ownerId), getCategories(ownerId, 'EXPENSE'), getCategories(ownerId, 'INCOME')]).then(([r, a, e, i]) => { setRecurring(r); setAccounts(a); setCategories([...e, ...i]) }) : config.actionTo === '/relatorios' ? Promise.all([getAnalytics(fromDate, toDate, ownerId), getCategoryAnalytics(fromDate, toDate, ownerId)]).then(([a, c]) => { setAnalytics(a); setCategoryAnalytics(c) }) : Promise.resolve()
    void load.catch(error => setLoadError(error instanceof Error ? error.message : t('financeLoadError'))).finally(() => setLoading(false))
  }, [ownerId, config.actionTo, refreshVersion, t])
  const isAccounts = config.actionTo === '/contas'; const isTransactions = config.actionTo === '/transacoes'; const isGoals = config.actionTo === '/metas'; const isCards = config.actionTo === '/cartoes'; const isCategories = config.actionTo === '/categorias'; const isBudgets = config.actionTo === '/orcamentos'; const isRecurring = config.actionTo === '/recorrentes'; const isReports = config.actionTo === '/relatorios'; const isSettings = config.actionTo === '/configuracoes'
  const saveMutation = useFinanceMutation(async (task: () => Promise<unknown>) => task())
  const save = async (task: () => Promise<unknown>) => { if (savingLock.current) return; savingLock.current = true; setSaving(true); setFormError(null); try { await saveMutation.mutateAsync(task); setModal(null); resetForm(); setRefreshVersion(version => version + 1) } catch (e) { setFormError(e instanceof Error ? e.message.replace('FINANCE_API_', t('apiErrorPrefix')) : t('saveError')); setRefreshVersion(version => version + 1) } finally { savingLock.current = false; setSaving(false) } }
  const selectedCategories = categories.filter(c => c.kind === transactionType)
  const categoryName = (id: string | null) => categories.find(c => c.id === id)?.name ?? t('noCategory')
  const accountName = (id: string) => accounts.find(a => a.id === id)?.name ?? t('account')
  const monthTransactions = transactions.filter(t => t.status !== 'CANCELLED')
  const filteredTransactions = monthTransactions.filter(tx => {
    const query = transactionSearch.trim().toLocaleLowerCase(getLocale())
    const matchesQuery = !query || tx.description.toLocaleLowerCase(getLocale()).includes(query) || accountName(tx.accountId).toLocaleLowerCase(getLocale()).includes(query) || categoryName(tx.categoryId).toLocaleLowerCase(getLocale()).includes(query)
    return matchesQuery && (!transactionAccountFilter || tx.accountId === transactionAccountFilter) && (transactionTypeFilter === 'ALL' || tx.type === transactionTypeFilter)
  })
  const incomeTotal = monthTransactions.filter(t => t.type === 'INCOME').reduce((s, t) => s + Number(t.amount), 0)
  const expenseTotal = monthTransactions.filter(t => t.type === 'EXPENSE').reduce((s, t) => s + Number(t.amount), 0)
  const visibleCategories = categoryTree(categories.filter(category => category.kind === categoryFilter))
  const budgetRows = budgets.map(budget => ({ budget, category: categories.find(category => category.id === budget.categoryId), spent: budgetSpent(budget, transactions) }))
  const budgetTotal = budgetRows.reduce((sum, row) => sum + Number(row.budget.limitAmount), 0)
  const budgetSpentTotal = budgetRows.reduce((sum, row) => sum + row.spent, 0)
  const activeRecurring = recurring.filter(item => item.active)
  const recurringIncome = activeRecurring.filter(item => item.transactionType === 'INCOME').reduce((sum, item) => sum + Number(item.amount || 0), 0)
  const recurringExpense = activeRecurring.filter(item => item.transactionType === 'EXPENSE').reduce((sum, item) => sum + Number(item.amount || 0), 0)
  const recurringNet = recurringIncome - recurringExpense
  const activeGoals = goals.filter(goal => goal.active)
  const goalTargetTotal = activeGoals.reduce((sum, goal) => sum + Number(goal.targetAmount || 0), 0)
  const goalCurrentTotal = activeGoals.reduce((sum, goal) => sum + Number(goal.currentAmount || 0), 0)
  const goalProgressTotal = goalTargetTotal > 0 ? Math.min(100, Math.round(goalCurrentTotal / goalTargetTotal * 100)) : 0
  const [titleKey, descKey] = pageTranslationKeys[config.actionTo] ?? ['pageGenericTitle','pageGenericDesc']
  return <main className="page"><Header title={t(titleKey)} desc={t(descKey)} action={config.actionTo === '/cartoes' ? <div className="header-actions"><button type="button" className="secondary" onClick={() => { resetForm(); setModal('cardPurchase') }}><Plus size={17} /> {t('purchase')}</button><button type="button" className="primary" onClick={() => { resetForm(); setModal('card') }}><Plus size={17} /> {t('card')}</button></div> : isSettings ? null : <button type="button" className="primary" onClick={() => { setFormError(null); resetForm(); setModal(isTransactions ? 'transaction' : isAccounts ? 'account' : isCategories ? 'category' : isBudgets ? 'budget' : isGoals ? 'goal' : isRecurring ? 'recurring' : null) }}><Plus size={17} /> {t('add')}</button>} />
    {isTransactions && <><div className="stat-grid"><Stat label={t('incomeMonth')} value={money(incomeTotal)} icon={ArrowDownLeft} /><Stat label={t('expenseMonth')} value={money(expenseTotal)} icon={ArrowUpRight} /><Stat label={t('movements')} value={String(monthTransactions.length)} icon={Receipt} /></div><section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('movements')}</span><h2>{t('thisMonth')}</h2></div><span className="badge">{filteredTransactions.length} / {monthTransactions.length}</span></div><div className="transaction-filters"><label className="field"><span>{t('search')}</span><input type="search" value={transactionSearch} onChange={e => setTransactionSearch(e.target.value)} placeholder={t('searchTransactions')} /></label><label className="field"><span>{t('account')}</span><select value={transactionAccountFilter} onChange={e => setTransactionAccountFilter(e.target.value)}><option value="">{t('allAccounts')}</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="field"><span>{t('type')}</span><select value={transactionTypeFilter} onChange={e => setTransactionTypeFilter(e.target.value as 'ALL' | 'INCOME' | 'EXPENSE')}><option value="ALL">{t('allTypes')}</option><option value="INCOME">{t('income')}</option><option value="EXPENSE">{t('expense')}</option></select></label><button type="button" className="text-button" onClick={() => { setTransactionSearch(''); setTransactionAccountFilter(''); setTransactionTypeFilter('ALL') }}>{t('clearFilters')}</button></div>{filteredTransactions.map(tx => <div className="account-row" key={tx.id}><i /><span><strong>{tx.description}</strong><small>{accountName(tx.accountId)} · {categoryName(tx.categoryId)} · {new Date(tx.occurredAt).toLocaleDateString(getLocale())}</small></span><b className={tx.type === 'INCOME' ? 'positive' : 'negative'}>{tx.type === 'INCOME' ? '+' : '-'} {money(Number(tx.amount))}</b><button type="button" className="text-button" disabled={saving || tx.status === 'CANCELLED'} onClick={() => { if (window.confirm(t('confirmCancelTransaction'))) void save(() => cancelTransaction(tx.id)) }}>{t('cancel')}</button></div>)}{!loading && !filteredTransactions.length && <div className="empty-inline">{monthTransactions.length ? t('noFilterResults') : t('noMovements')}</div>}</section></>}
    {isAccounts && <><section className="feature-grid">{accounts.map(account => { const latest = reconciliationRuns.find(run => run.accountId === account.id); return <article className="feature-card" key={account.id}><div className="feature-icon"><Wallet size={18} /></div><div><strong>{account.name}</strong><span>{account.accountType} · {account.currency}</span><small>{latest ? `${t('reconciliation')}: ${latest.status === 'MATCHED' ? t('reconciliationMatched') : t('reconciliationDiverged')} · ${t('difference')} ${money(Number(latest.difference), account.currency)}` : t('noReconciliationForAccount')}</small></div><b>{money(Number(account.currentBalance), account.currency)}</b><button type="button" className="text-button" disabled={saving} onClick={() => void save(() => reconcileAccount(account.id))}>{t('reconcileAccount')}</button></article>})}{!loading && !accounts.length && <div className="panel empty-state"><Wallet size={30} /><div><strong>{t('noAccountsRegistered')}</strong><p>{t('addFirstAccount')}</p></div></div>}</section><section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('reconciliation')}</span><h2>{t('reconciliationHistory')}</h2></div><span className="badge">{reconciliationRuns.length}</span></div>{reconciliationRuns.slice(0,10).map(run => <div className="account-row" key={run.id}><i /><span><strong>{accountName(run.accountId)}</strong><small>{run.status === 'MATCHED' ? t('reconciliationMatched') : t('reconciliationDiverged')}</small></span><b className={run.status === 'MATCHED' ? 'positive' : 'negative'}>{money(Number(run.difference), accounts.find(a => a.id === run.accountId)?.currency ?? 'BRL')}</b></div>)}{!loading && !reconciliationRuns.length && <div className="empty-inline">{t('noReconciliation')}</div>}</section></>}
    {isGoals && <><div className="stat-grid"><Stat label={t('goalsValue')} value={money(goalTargetTotal)} icon={Target} /><Stat label={t('alreadySaved')} value={money(goalCurrentTotal)} icon={Wallet} /><Stat label={t('overallProgress')} value={`${goalProgressTotal}%`} icon={BarChart3} /></div><section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('objectives')}</span><h2>{t('goalsProgress')}</h2></div><span className="badge">{t('activeItems',{count:activeGoals.length})}</span></div>{activeGoals.map(goal => { const target = Number(goal.targetAmount || 0); const current = Number(goal.currentAmount || 0); const percent = target > 0 ? Math.min(100, Math.round(current / target * 100)) : 0; const days = goal.targetDate ? Math.ceil((new Date(goal.targetDate).getTime() - Date.now()) / 86400000) : null; return <div className="budget-row" key={goal.id}><div className="budget-row-head"><span><strong>{goal.name}</strong><small>{money(current)} de {money(target)} · {goal.targetDate ? (days !== null && days >= 0 ? t('daysRemaining', { count: days }) : t('deadlineClosed')) : t('noDeadline')}</small></span><span className="positive">{percent}%</span></div><div className="budget-progress"><span style={{ width: `${percent}%` }} /></div><div className="budget-row-meta"><span>{t('missingAmount', { amount: money(Math.max(0, target - current)) })}</span><strong>{goal.targetDate ? new Date(goal.targetDate).toLocaleDateString(getLocale()) : t('noTargetDate')}</strong></div></div> })}{!loading && !activeGoals.length && <div className="empty-inline">{t('noActiveGoals')}</div>}</section></>}
    {isReports && analytics && <><div className="stat-grid"><Stat label={t('incomeMonth')} value={money(Number(analytics.income))} icon={ArrowDownLeft} /><Stat label={t('expenseMonth')} value={money(Number(analytics.expense))} icon={ArrowUpRight} /><Stat label={t('netFlow')} value={money(Number(analytics.cashFlow))} icon={BarChart3} /><Stat label={t('netWorth')} value={money(Number(analytics.netWorth))} icon={Wallet} /></div><div className="stat-grid"><Stat label={t('assets')} value={money(Number(analytics.assets))} icon={ArrowDownLeft} /><Stat label={t('liabilities')} value={money(Number(analytics.liabilities))} icon={ArrowUpRight} /><Stat label={t('savingsRate')} value={`${Number(analytics.savingsRate).toFixed(1)}%`} icon={Target} /></div><section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('analysis')}</span><h2>{t('expensesByCategory')}</h2></div><span className="badge">{t('savingsRate')} {Number(analytics.savingsRate).toFixed(1)}%</span></div>{Object.entries(categoryAnalytics).sort((a,b) => b[1]-a[1]).map(([label,value]) => <div className="account-row" key={label}><i /><span><strong>{label}</strong><small>{t('periodShare')}</small></span><b>{money(Number(value))}</b></div>)}{!Object.keys(categoryAnalytics).length && <div className="empty-inline">{t('noExpenses')}</div>}</section></>}
    {isRecurring && <><div className="stat-grid"><Stat label={t('activeIncome')} value={money(recurringIncome)} icon={ArrowDownLeft} /><Stat label={t('activeExpenses')} value={money(recurringExpense)} icon={ArrowUpRight} /><Stat label={t('recurringBalance')} value={money(recurringNet)} icon={BarChart3} /></div><section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('recurrences')}</span><h2>{t('scheduledCommitments')}</h2></div><span className="badge">{t('activeItems', { count: activeRecurring.length })}</span></div>{recurring.map(item => <div className="account-row" key={item.id}><i /><span><strong>{item.description}</strong><small>{accountName(item.accountId)} · {categoryName(item.categoryId)} · {item.frequency} · {t('nextOccurrence').toLowerCase()} {new Date(item.nextOccurrence).toLocaleDateString(getLocale())}{item.endDate ? ` · ${t('until')} ${new Date(item.endDate).toLocaleDateString(getLocale())}` : ''}</small></span><b className={item.transactionType === 'INCOME' ? 'positive' : 'negative'}>{item.transactionType === 'INCOME' ? '+' : '-'} {money(Number(item.amount))}</b><button type="button" className="text-button" onClick={() => void save(() => item.active ? pauseRecurring(item.id) : resumeRecurring(item.id))}>{item.active ? t('pause') : t('resume')}</button></div>)}{!loading && !recurring.length && <div className="empty-inline">{t('noRecurring')}</div>}</section></>}
    {isCards && <><div className="feature-grid">{cards.map(card => <article className="feature-card" key={card.id}><div className="feature-icon"><CreditCard size={18} /></div><div><strong>{card.name} {card.lastFour ? `•••• ${card.lastFour}` : ''}</strong><span>{card.brand || t('card')} · {t('limit')} {money(card.creditLimit)} · {t('available')} {money(Math.max(0, Number(card.creditLimit) - invoices.filter(invoice => invoice.cardId === card.id && invoice.status !== 'PAID').reduce((sum, invoice) => sum + Math.max(0, Number(invoice.totalAmount) - Number(invoice.paidAmount)), 0)))} · {t('closingDay')} {card.closingDay} · {t('dueDay')} {card.dueDay}</span></div><span className="badge">{card.status}</span></article>)}{!loading && !cards.length && <div className="panel empty-state"><CreditCard size={30} /><div><strong>{t('noCards')}</strong><p>{t('addFirstCard')}</p></div></div>}</div><section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('invoices')}</span><h2>{t('upcomingDue')}</h2></div></div>{invoices.slice(0, 8).map(invoice => <div className="account-row" key={invoice.id}><i /><span><strong>{invoice.referenceMonth}</strong><small>{invoice.status} · {t('due')} {new Date(invoice.dueDate).toLocaleDateString(getLocale())} · {t('paid')} {money(invoice.paidAmount)}</small></span><b>{money(invoice.totalAmount)}</b><button type="button" className="text-button" onClick={() => { setSelectedInvoice(invoice.id); void getInvoicePurchases(invoice.id).then(setPurchases).catch(() => setPurchases([])) }}>{t('purchases')}</button>{invoice.status === 'OPEN' && <button type="button" className="text-button" onClick={() => void save(() => closeInvoice(invoice.id, ownerId ?? ''))}>{t('closeInvoice')}</button>}{invoice.status !== 'PAID' && <button type="button" className="text-button" onClick={() => { setInvoicePaymentId(invoice.id); setAccountId(accounts[0]?.id ?? ''); setFormError(null); setModal('invoicePayment') }}>{t('pay')}</button>}</div>)}{!loading && !invoices.length && <div className="empty-inline">{t('noInvoices')}</div>}</section>{selectedInvoice && <section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('invoicePurchases')}</span><h2>{invoices.find(i => i.id === selectedInvoice)?.referenceMonth}</h2></div><button type="button" className="text-button" onClick={() => setSelectedInvoice(null)}>{t('close')}</button></div>{purchases.map(p => <div className="account-row" key={p.id}><i /><span><strong>{p.description}</strong><small>{t('installment')} {p.installmentNumber}/{p.totalInstallments} · {new Date(p.purchasedAt).toLocaleDateString(getLocale())}</small></span><b>{money(p.installmentAmount)}</b></div>)}</section>}</>}
    {isCategories && <section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('organization')}</span><h2>{t('categoriesAndSubcategories')}</h2></div><div className="header-actions"><button type="button" className={categoryFilter === 'EXPENSE' ? 'secondary' : 'text-button'} onClick={() => setCategoryFilter('EXPENSE')}>{t('expense')}</button><button type="button" className={categoryFilter === 'INCOME' ? 'secondary' : 'text-button'} onClick={() => setCategoryFilter('INCOME')}>{t('income')}</button></div></div>{visibleCategories.map(category => <div className="account-row" key={category.id} style={{ paddingLeft: category.parentId ? 32 : 12 }}><i /><span><strong>{category.name}</strong><small>{category.parentId ? t('subcategoryOf', { name: categoryName(category.parentId) }) : t('mainCategory')}</small></span><b className="badge">{category.kind === 'EXPENSE' ? t('expense') : t('income')}</b></div>)}{!loading && !visibleCategories.length && <div className="empty-inline">{t('noCategories')}</div>}</section>}
    {isBudgets && <><div className="stat-grid"><Stat label={t('plannedLimit')} value={money(budgetTotal)} icon={Target} /><Stat label={t('alreadyUsed')} value={money(budgetSpentTotal)} icon={ArrowUpRight} /><Stat label={t('available')} value={money(Math.max(0, budgetTotal - budgetSpentTotal))} icon={Wallet} /></div><section className="panel data-panel"><div className="section-title"><div><span className="eyebrow">{t('planning')}</span><h2>{t('budgetsByCategory')}</h2></div><span className="badge">{budgetRows.length} {t('categoriesCount')}</span></div>{budgetRows.map(({ budget, category, spent }) => { const percent = budgetPercent(spent, Number(budget.limitAmount)); const over = spent > Number(budget.limitAmount); return <div className="budget-row" key={budget.id}><div className="budget-row-head"><span><strong>{category?.name ?? t('categoryNotFound')}</strong><small>{budget.period} · {t('start')} {new Date(budget.periodStart).toLocaleDateString(getLocale())}</small></span><span className={over ? 'negative' : 'positive'}>{over ? t('aboveLimit') : t('usedPercent', { percent })}</span></div><div className="budget-progress"><span style={{ width: `${Math.min(100, percent)}%` }} /></div><div className="budget-row-meta"><span>{money(spent)} de {money(Number(budget.limitAmount))}</span><strong className={over ? 'negative' : ''}>{over ? t('exceeded', { amount: money(spent - Number(budget.limitAmount)) }) : t('remaining', { amount: money(budgetRemaining(spent, Number(budget.limitAmount))) })}</strong></div></div> })}{!loading && !budgetRows.length && <div className="empty-inline">{t('noBudget')}</div>}</section></>}
    
    {isSettings && <section className="panel"><div className="section-title"><div><span className="eyebrow">{t('account')}</span><h2>{t('preferences')}</h2></div></div><div className="feature-grid"><article className="feature-card"><div className="feature-icon"><Sparkles size={18} /></div><div><strong>{t('language')}</strong><span>{t('languageDescription')}</span></div><LanguageSwitcher /></article></div></section>}
    {!isAccounts && !isTransactions && !isGoals && !isCards && !isCategories && !isBudgets && !isRecurring && !isReports && !isSettings && <><div className="feature-grid">{config.itemKeys.map((itemKey, index) => <NavLink className="feature-card" to={config.itemRoutes[index] ?? config.actionTo} key={itemKey}><div className="feature-icon"><config.icon size={18} /></div><div><strong>{t(itemKey)}</strong><span>{t('controlledFlow')}</span></div><ChevronRight size={16} /></NavLink>)}</div></>}
    {modal === 'card' && <Modal title={t('newCard')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!ownerId || !name.trim() || !isPositiveAmount(creditLimit)) return setFormError(t('errorCardRequired')); if (lastFour && !/^\\d{4}$/.test(lastFour)) return setFormError(t('errorCardRequired')); if (![closingDay, dueDay].every(day => Number.isInteger(Number(day)) && Number(day) >= 1 && Number(day) <= 31)) return setFormError(t('errorCardRequired')); void save(() => createCard({ ownerId, name: name.trim(), brand: cardBrand, lastFour, creditLimit: Number(creditLimit), closingDay: Number(closingDay), dueDay: Number(dueDay) })) }}><Field label={t('name')}><input value={name} onChange={e => setName(e.target.value)} placeholder={t('placeholderCard')} /></Field><Field label={t('brand')}><select value={cardBrand} onChange={e => setCardBrand(e.target.value)}><option>Visa</option><option>Mastercard</option><option>Elo</option><option>American Express</option></select></Field><Field label={t('lastFour')}><input maxLength={4} value={lastFour} onChange={e => setLastFour(e.target.value.replace(/\D/g, '').slice(0,4))} /></Field><Field label={t('limit')}><input type="number" min="0.01" step="0.01" value={creditLimit} onChange={e => setCreditLimit(e.target.value)} /></Field><Field label={t('closingDay')}><input type="number" min="1" max="31" value={closingDay} onChange={e => setClosingDay(e.target.value)} /></Field><Field label={t('dueDay')}><input type="number" min="1" max="31" value={dueDay} onChange={e => setDueDay(e.target.value)} /></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('createCard')}</button></form></Modal>}
    {modal === 'cardPurchase' && <Modal title={t('newCardPurchase')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!ownerId || !cardId || !description.trim() || !isPositiveAmount(amount)) return setFormError(t('errorCardPurchaseRequired')); void save(() => createCardPurchase({ ownerId, cardId, description: description.trim(), totalAmount: Number(amount), installments: Number(installments), purchasedAt: localDateKey() })) }}><Field label={t('card')}><select value={cardId} onChange={e => setCardId(e.target.value)}><option value="">{t('select')}</option>{cards.map(c => <option key={c.id} value={c.id}>{c.name} •••• {c.lastFour}</option>)}</select></Field><Field label={t('description')}><input value={description} onChange={e => setDescription(e.target.value)} placeholder={t('placeholderPurchase')} /></Field><Field label={t('totalAmount')}><input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label={t('installments')}><input type="number" min="1" max="60" value={installments} onChange={e => setInstallments(e.target.value)} /></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('createPurchase')}</button></form></Modal>}
    {modal === 'invoicePayment' && <Modal title={t('payInvoice')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!ownerId || !invoicePaymentId || !accountId) return setFormError(t('errorPaymentAccountRequired')); void save(() => payInvoice(invoicePaymentId, ownerId, accountId)) }}><Field label={t('invoice')}><input value={invoices.find(i => i.id === invoicePaymentId)?.referenceMonth ?? ''} readOnly /></Field><Field label={t('paymentAccount')}><select value={accountId} onChange={e => setAccountId(e.target.value)}><option value="">{t('select')}</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.name} · {money(Number(account.currentBalance), account.currency)}</option>)}</select></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('confirmPayment')}</button></form></Modal>}
    {modal === 'transaction' && <Modal title={t('newTransactionModal')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!ownerId || !accountId || !categoryId || !description.trim() || !isPositiveAmount(amount)) return setFormError(t('errorTransactionRequired')); void save(() => createTransaction({ accountId, categoryId, description: description.trim(), amount: Number(amount), type: transactionType, occurredAt: new Date(`${occurredAtDate}T12:00:00`).toISOString(), externalId: transactionExternalId })) }}><Field label={t('type')}><select value={transactionType} onChange={e => { const value = e.target.value as 'INCOME' | 'EXPENSE'; setTransactionType(value); setCategoryId('') }}><option value="EXPENSE">{t('expense')}</option><option value="INCOME">{t('income')}</option></select></Field><Field label={t('account')}><select value={accountId} onChange={e => setAccountId(e.target.value)}><option value="">{t('select')}</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label={t('category')}><select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">{t('select')}</option>{selectedCategories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label={t('description')}><input value={description} onChange={e => setDescription(e.target.value)} placeholder={t('placeholderTransaction')} /></Field><Field label={t('amount')}><input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0,00" /></Field><Field label={t('date')}><input type="date" required value={occurredAtDate} onChange={e => setOccurredAtDate(e.target.value)} /></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('saveTransaction')}</button></form></Modal>}
    {modal === 'account' && <Modal title={t('newAccount')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); const submittedName = [new FormData(e.currentTarget).get('accountName'), accountNameInput.current?.value, accountNameValue].map(value => String(value ?? '').trim()).find(Boolean) ?? ''; if (!ownerId) return setFormError(t('loginToLoadData')); if (!submittedName) return setFormError(t('errorAccountNameRequired')); if (!Number.isFinite(Number(openingBalance || 0))) return setFormError(t('saveError')); void save(() => createAccount({ ownerId, name: submittedName, accountType, currency, openingBalance: Number(openingBalance || 0) })) }}><Field label={t('name')}><input ref={accountNameInput} name="accountName" autoComplete="off" required maxLength={120} value={accountNameValue} onChange={e => setAccountNameValue(e.target.value)} onInput={e => setAccountNameValue(e.currentTarget.value)} placeholder={t('placeholderAccount')} /></Field><Field label={t('type')}><select value={accountType} onChange={e => setAccountType(e.target.value)}><option value="CHECKING">{t('checking')}</option><option value="SAVINGS">{t('savingsAccount')}</option><option value="CASH">{t('wallet')}</option><option value="INVESTMENT">{t('investments')}</option><option value="OTHER">{t('other')}</option></select></Field><Field label={t('currency')}><select value={currency} onChange={e => setCurrency(e.target.value)}><option value="BRL">BRL</option><option value="EUR">EUR</option><option value="USD">USD</option></select></Field><Field label={t('openingBalance')}><input type="number" step="0.01" value={openingBalance} onChange={e => setOpeningBalance(e.target.value)} /></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('createAccount')}</button></form></Modal>}
    {modal === 'category' && <Modal title={t('newCategory')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!ownerId || !name.trim()) return setFormError(t('errorCategoryNameRequired')); void save(() => createCategory({ ownerId, name: name.trim(), kind: categoryKind, parentId: parentCategoryId || null })) }}><Field label={t('name')}><input value={name} onChange={e => setName(e.target.value)} placeholder={t('placeholderCategory')} /></Field><Field label={t('type')}><select value={categoryKind} onChange={e => { const kind = e.target.value as FinanceCategory['kind']; setCategoryKind(kind); setParentCategoryId('') }}><option value="EXPENSE">{t('expense')}</option><option value="INCOME">{t('income')}</option></select></Field><Field label={t('mainCategory')}><select value={parentCategoryId} onChange={e => setParentCategoryId(e.target.value)}><option value="">{t('noParentCategory')}</option>{categories.filter(c => c.kind === categoryKind && !c.parentId).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('createCategory')}</button></form></Modal>}
    {modal === 'budget' && <Modal title={t('newBudget')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!ownerId || !categoryId || !isPositiveAmount(amount)) return setFormError(t('errorBudgetRequired')); void save(() => createBudget({ ownerId, categoryId, period, periodStart: periodStartFor(period).toISOString(), limitAmount: Number(amount) })) }}><Field label={t('category')}><select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">{t('select')}</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label={t('period')}><select value={period} onChange={e => setPeriod(e.target.value as FinanceBudget['period'])}><option value="MONTHLY">{t('monthly')}</option><option value="WEEKLY">{t('weekly')}</option><option value="YEARLY">{t('yearly')}</option></select></Field><Field label={t('limit')}><input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('createBudget')}</button></form></Modal>}
    {modal === 'recurring' && <Modal title={t('newRecurring')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!accountId || !description.trim() || !isPositiveAmount(amount)) return setFormError(t('errorRecurringRequired')); if (endDate && endDate < nextOccurrence) return setFormError(t('errorRecurringDate')); void save(() => createRecurring({ accountId, categoryId: categoryId || null, description: description.trim(), amount: Number(amount), transactionType, frequency, nextOccurrence, endDate: endDate || null })) }}><Field label={t('type')}><select value={transactionType} onChange={e => { setTransactionType(e.target.value as 'INCOME' | 'EXPENSE'); setCategoryId('') }}><option value="EXPENSE">{t('expense')}</option><option value="INCOME">{t('income')}</option></select></Field><Field label={t('account')}><select value={accountId} onChange={e => setAccountId(e.target.value)}><option value="">{t('select')}</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label={t('category')}><select value={categoryId} onChange={e => setCategoryId(e.target.value)}><option value="">{t('noCategory')}</option>{selectedCategories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label={t('description')}><input value={description} onChange={e => setDescription(e.target.value)} placeholder={t('placeholderRecurring')} /></Field><Field label={t('amount')}><input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label={t('frequency')}><select value={frequency} onChange={e => setFrequency(e.target.value)}><option value="DAILY">{t('daily')}</option><option value="WEEKLY">{t('weekly')}</option><option value="MONTHLY">{t('monthly')}</option><option value="YEARLY">{t('yearly')}</option></select></Field><Field label={t('nextOccurrence')}><input type="date" value={nextOccurrence} onChange={e => setNextOccurrence(e.target.value)} /></Field><Field label={t('endDateOptional')}><input type="date" min={nextOccurrence} value={endDate} onChange={e => setEndDate(e.target.value)} /></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('createRecurring')}</button></form></Modal>}
    {modal === 'goal' && <Modal title={t('newGoal')} onClose={() => setModal(null)}><form className="form-grid" onSubmit={e => { e.preventDefault(); if (!ownerId || !name.trim() || !isPositiveAmount(amount)) return setFormError(t('errorGoalRequired')); void save(() => createGoal({ ownerId, name: name.trim(), targetAmount: Number(amount), targetDate: targetDate ? new Date(`${targetDate}T23:59:59`).toISOString() : null })) }}><Field label={t('name')}><input value={name} onChange={e => setName(e.target.value)} placeholder={t('placeholderGoal')} /></Field><Field label={t('targetAmount')}><input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} /></Field><Field label={t('targetDate')}><input type="date" value={targetDate} onChange={e => setTargetDate(e.target.value)} /></Field>{formError && <div className="form-error" role="alert">{formError}</div>}<button type="submit" className="primary form-submit" disabled={saving}>{saving ? t('saving') : t('createGoal')}</button></form></Modal>}
  </main>
}