package com.kovian.finance.ai.api;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import com.kovian.finance.transaction.domain.*;
import com.kovian.finance.transaction.repository.FinancialTransactionRepository;
import com.kovian.finance.account.repository.FinancialAccountRepository;
import java.math.*;

@RestController
@RequestMapping("/api/v1/internal/kovi")
public class KoviFinanceInternalController {
 private final FinancialAiContextController context; private final FinancialTransactionRepository transactions; private final FinancialAccountRepository accounts; private final String apiKey;
 public KoviFinanceInternalController(FinancialAiContextController context,FinancialTransactionRepository transactions,FinancialAccountRepository accounts,@Value("${kovian.kovi.internal-api-key:}")String apiKey){this.context=context;this.transactions=transactions;this.accounts=accounts;this.apiKey=apiKey;}
 @GetMapping("/capabilities")
 public Map<String,Object> capabilities(@RequestHeader(value="X-KOVI-INTERNAL-KEY",required=false)String key){authorize(key);return Map.of("source","kovian-finance","domain","finance","contractVersion","1.3","capabilities",List.of("finance.get_balance","finance.list_transactions","finance.get_revenue","finance.get_context","finance.get_context_summary","finance.get_forecast","finance.list_accounts"),"mutations",List.of());}
 @GetMapping("/accounts")
 public List<Map<String,Object>> accounts(@RequestHeader(value="X-KOVI-INTERNAL-KEY",required=false)String key,@RequestParam UUID ownerId){authorize(key);return accounts.findByOwnerIdOrderByName(ownerId).stream().map(a->Map.<String,Object>of("id",a.getId().toString(),"name",a.getName(),"type",a.getAccountType().name(),"currency",a.getCurrency(),"balance",a.getCurrentBalance(),"status",a.getStatus().name())).toList();}
 @GetMapping("/transactions")
 public List<Map<String,Object>> transactions(@RequestHeader(value="X-KOVI-INTERNAL-KEY",required=false)String key,@RequestParam UUID ownerId,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(defaultValue="50")int limit){authorize(key);if(limit<1||limit>100)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Transaction limit must be between 1 and 100.");var start=(from==null?LocalDate.now().minusDays(90):from).atStartOfDay().atOffset(ZoneOffset.UTC);var end=(to==null?LocalDate.now():to.plusDays(1)).atStartOfDay().atOffset(ZoneOffset.UTC);if(end.isBefore(start)||Duration.between(start,end).toDays()>366)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Transaction window must be between 0 and 366 days.");return transactions.findByOwnerIdAndOccurredAtBetweenOrderByOccurredAtDesc(ownerId,start,end).stream().filter(t->t.getStatus()!=TransactionStatus.CANCELLED).limit(limit).map(t->Map.<String,Object>of("id",t.getId().toString(),"occurredAt",t.getOccurredAt().toString(),"description",t.getDescription(),"amount",t.getAmount(),"type",t.getTransactionType().name(),"status",t.getStatus().name())).toList();}
 @GetMapping("/revenue")
 public Map<String,Object> revenue(@RequestHeader(value="X-KOVI-INTERNAL-KEY",required=false)String key,@RequestParam LocalDate from,@RequestParam LocalDate to,@RequestParam UUID ownerId){authorize(key);if(to.isBefore(from)||Duration.between(from.atStartOfDay(),to.plusDays(1).atStartOfDay()).toDays()>366)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Revenue window must be between 0 and 366 days.");var start=from.atStartOfDay().atOffset(ZoneOffset.UTC);var end=to.plusDays(1).atStartOfDay().atOffset(ZoneOffset.UTC);BigDecimal income=BigDecimal.ZERO,expense=BigDecimal.ZERO;for(var t:transactions.findByOwnerIdAndOccurredAtBetweenOrderByOccurredAtDesc(ownerId,start,end)){if(t.getStatus()==TransactionStatus.CANCELLED)continue;if(t.getTransactionType()==TransactionType.INCOME)income=income.add(t.getAmount());else if(t.getTransactionType()==TransactionType.EXPENSE)expense=expense.add(t.getAmount());}return Map.of("source","kovian-finance","contractVersion","1.3","readOnly",true,"ownerId",ownerId.toString(),"from",from.toString(),"to",to.toString(),"income",income,"expense",expense,"net",income.subtract(expense));}
 @GetMapping("/context/summary")
 public Map<String,Object> summary(@RequestHeader(value="X-KOVI-INTERNAL-KEY",required=false)String key,@RequestParam UUID ownerId,@RequestParam LocalDate from,@RequestParam LocalDate to){authorize(key);return context.summary(ownerId,from,to);}
 @GetMapping("/context")
 public Map<String,Object> context(@RequestHeader(value="X-KOVI-INTERNAL-KEY",required=false)String key,@RequestParam UUID ownerId,@RequestParam LocalDate from,@RequestParam LocalDate to){authorize(key);return context.context(ownerId,from,to);}
 @GetMapping("/forecast")
 public Map<String,Object> forecast(@RequestHeader(value="X-KOVI-INTERNAL-KEY",required=false)String key,@RequestParam UUID ownerId,@RequestParam LocalDate from,@RequestParam int days){authorize(key);if(days<1||days>365)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Forecast horizon must be between 1 and 365 days.");var start=from.minusDays(90).atStartOfDay().atOffset(ZoneOffset.UTC);var end=from.atStartOfDay().atOffset(ZoneOffset.UTC);BigDecimal income=BigDecimal.ZERO,expense=BigDecimal.ZERO;for(var tx:transactions.findByOwnerIdAndOccurredAtBetweenOrderByOccurredAtDesc(ownerId,start,end)){if(tx.getStatus()==TransactionStatus.CANCELLED)continue;if(tx.getTransactionType()==TransactionType.INCOME)income=income.add(tx.getAmount());else if(tx.getTransactionType()==TransactionType.EXPENSE)expense=expense.add(tx.getAmount());}var dailyIncome=income.divide(BigDecimal.valueOf(90),4,RoundingMode.HALF_UP),dailyExpense=expense.divide(BigDecimal.valueOf(90),4,RoundingMode.HALF_UP);var balance=accounts.findByOwnerIdOrderByName(ownerId).stream().map(a->a.getCurrentBalance()).reduce(BigDecimal.ZERO,BigDecimal::add);var points=new ArrayList<Map<String,Object>>();for(int i=0;i<days;i++){balance=balance.add(dailyIncome).subtract(dailyExpense);points.add(Map.of("date",from.plusDays(i).toString(),"income",dailyIncome,"expense",dailyExpense,"net",dailyIncome.subtract(dailyExpense),"projectedBalance",balance));}return Map.of("source","kovian-finance","contractVersion","1.3","readOnly",true,"ownerId",ownerId.toString(),"horizonDays",days,"points",points);}
 private void authorize(String provided){if(apiKey==null||apiKey.length()<32||provided==null||!MessageDigest.isEqual(apiKey.getBytes(StandardCharsets.UTF_8),provided.getBytes(StandardCharsets.UTF_8)))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid KOVI internal credential.");}
}