import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

const resources = {
  'pt-BR': { common: {
    language: 'Português', financeName:'Finance', fitness:'Fitness', koviAi:'KOVI AI', closeMenu:'Fechar menu', search:'Buscar', searchFinance:'Buscar no KOVIAN Finance...', noResults:'Nenhum resultado encontrado.', escToClose:'Esc para fechar', financeLoadError:'Não foi possível carregar os dados financeiros.', loginToLoadFinance:'Faça login para carregar seus dados financeiros.', newTransaction:'Nova transação', consolidatedBalance:'Saldo consolidado BRL', loading:'Carregando...', syncedAccounts:'{{count}} conta(s) sincronizada(s)', income90:'Receitas · 90 dias', expense90:'Despesas · 90 dias', activeGoals:'Metas ativas', connectedAccounts:'Contas conectadas', viewAll:'Ver todas', noAccounts:'Nenhuma conta cadastrada.', quickAccess:'ACESSO RÁPIDO', organize:'Organizar', manageBalances:'Gerencie saldos.', trackInOut:'Acompanhe entradas e saídas.', trackGoals:'Acompanhe objetivos.', analyzePeriods:'Analise períodos.', controlTitle:'Fechamento e reconciliação', controlDesc:'Controle operacional, exceções, evidências e exportações governadas.', newReview:'Nova revisão', currentPeriod:'Período atual', currentMonth:'Setembro 2026', lastRun:'Última execução', noRunRecorded:'Nenhuma execução registrada', reconciliation:'Reconciliação', runsRecorded:'execução(ões) registradas', runs:'execução(ões)', exports:'Exportações', controlled:'Controlados', exportDetail:'Escopo, expiração e checksum', close:'Fechamento', periodDates:'01/09/2026 → 30/09/2026', operationalReview:'Revisão operacional', backendBalances:'Saldos e movimentos permanecem sob controle do backend', persistedReconciliations:'Reconciliações possuem histórico persistido', exceptionsBeforeClose:'Exceções exigem investigação antes do fechamento', reconciliationHistory:'Histórico de reconciliação', refresh:'Atualizar', loadFailure:'Falha ao carregar dados', noReconciliation:'Nenhuma reconciliação registrada', runFirstReconciliation:'Execute a primeira reconciliação pelo fluxo operacional.', account:'Conta', expected:'Esperado', actual:'Atual', difference:'Diferença', financialExports:'Exportações financeiras', exportBackend:'Escopo, expiração e checksum controlados pelo backend.', availableBackend:'Disponível no backend', exportSourceOfTruth:'O painel não fabrica dados de exportação localmente: a fonte de verdade continua sendo o domínio Finance.', reconciliationLoadError:'Não foi possível carregar a reconciliação.', overview: 'Visão geral', chat: 'Conversar com KOVI', projects: 'Projetos',
    development: 'Desenvolvimento', research: 'Pesquisa', automations: 'Automações', integrations: 'Integrações', settings: 'Configurações',
    principal: 'Principal', work: 'Trabalho', system: 'Sistema', online: 'Online', newProject: 'Novo projeto',
    dashboardTitle: 'Seu centro de comando inteligente.', dashboardDesc: 'Orquestre projetos, agentes e automações sem começar por configurações técnicas.',
    status: 'Status do KOVI', ready: 'Operação pronta para continuar', chatTitle: 'Conversar com KOVI',
    financeOverview: 'Visão geral', accounts: 'Contas', transactions: 'Transações', goals: 'Metas e orçamento',
    reports: 'Relatórios', subscriptions: 'Assinaturas', cards: 'Cartões', budgets: 'Orçamentos', recurring: 'Recorrentes', categories: 'Categorias', financeIntegrations: 'Integrações', financeSettings: 'Configurações', more: 'Mais', group_principal: 'Principal', group_planejamento: 'Planejamento', group_organizacao: 'Organização', group_sistema: 'Sistema'
  }},
  en: { common: {
    language: 'English', financeName:'Finance', fitness:'Fitness', koviAi:'KOVI AI', closeMenu:'Close menu', search:'Search', searchFinance:'Search KOVIAN Finance...', noResults:'No results found.', escToClose:'Esc to close', financeLoadError:'Unable to load financial data.', loginToLoadFinance:'Sign in to load your financial data.', newTransaction:'New transaction', consolidatedBalance:'Consolidated BRL balance', loading:'Loading...', syncedAccounts:'{{count}} account(s) synchronized', income90:'Income · 90 days', expense90:'Expenses · 90 days', activeGoals:'Active goals', connectedAccounts:'Connected accounts', viewAll:'View all', noAccounts:'No accounts registered.', quickAccess:'QUICK ACCESS', organize:'Organize', manageBalances:'Manage balances.', trackInOut:'Track income and expenses.', trackGoals:'Track goals.', analyzePeriods:'Analyze periods.', controlTitle:'Close & reconciliation', controlDesc:'Operational control, exceptions, evidence and governed exports.', newReview:'New review', currentPeriod:'Current period', currentMonth:'September 2026', lastRun:'Last run', noRunRecorded:'No execution recorded', reconciliation:'Reconciliation', runsRecorded:'execution(s) recorded', runs:'execution(s)', exports:'Exports', controlled:'Controlled', exportDetail:'Scope, expiration and checksum', close:'Close', periodDates:'09/01/2026 → 09/30/2026', operationalReview:'Operational review', backendBalances:'Balances and movements remain controlled by the backend', persistedReconciliations:'Reconciliations have persisted history', exceptionsBeforeClose:'Exceptions require investigation before closing', reconciliationHistory:'Reconciliation history', refresh:'Refresh', loadFailure:'Failed to load data', noReconciliation:'No reconciliation recorded', runFirstReconciliation:'Run the first reconciliation through the operational flow.', account:'Account', expected:'Expected', actual:'Actual', difference:'Difference', financialExports:'Financial exports', exportBackend:'Scope, expiration and checksum controlled by the backend.', availableBackend:'Available in backend', exportSourceOfTruth:'The panel does not fabricate export data locally: Finance remains the source of truth.', reconciliationLoadError:'Unable to load reconciliation.', overview: 'Overview', chat: 'Chat with KOVI', projects: 'Projects',
    development: 'Development', research: 'Research', automations: 'Automations', integrations: 'Integrations', settings: 'Settings',
    principal: 'Main', work: 'Work', system: 'System', online: 'Online', newProject: 'New project',
    dashboardTitle: 'Your intelligent command center.', dashboardDesc: 'Orchestrate projects, agents and automations without starting with technical configuration.',
    status: 'KOVI status', ready: 'Operation ready to continue', chatTitle: 'Chat with KOVI',
    financeOverview: 'Overview', accounts: 'Accounts', transactions: 'Transactions', goals: 'Goals & budget',
    reports: 'Reports', subscriptions: 'Subscriptions', cards: 'Cards', budgets: 'Budgets', recurring: 'Recurring', categories: 'Categories', financeIntegrations: 'Integrations', financeSettings: 'Settings', more: 'More', group_principal: 'Main', group_planejamento: 'Planning', group_organizacao: 'Organization', group_sistema: 'System'
  }},
}
void i18n.use(LanguageDetector).use(initReactI18next).init({
  resources, fallbackLng: 'pt-BR', supportedLngs: ['pt-BR', 'en'], load: 'currentOnly',
  defaultNS: 'common', ns: ['common'],
  detection: { order: ['localStorage', 'navigator'], caches: ['localStorage'], lookupLocalStorage: 'kovian-language' },
  interpolation: { escapeValue: false }, react: { useSuspense: false },
})
export default i18n